# Site settings
title:          Ting's blog
description:    TIL note
url:            https://Ting-kim.github.io

# Author
author:
  name:         Ting-kim
  email:        ting_916@naver.com
  url:          https://Ting-kim.github.io

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: ting_916@naver.com
  github: https://github.com/Ting-kim

# Math equation
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false